apiVersion: apps/v1
kind: Deployment

metadata:
  name: mymodel-deployment
  labels:
    app: mymodel

spec:
  replicas: 3
  selector:
    matchLabels:
      app: mymodel
  template:
    metadata:
      labels:
        app: mymodel
    spec:
      containers:
      - name: mymodel
        image: rabishankarsahu/mymodel:latest
        ports:
        - containerPort: 5000
